<a href="https://colab.research.google.com/github/MuhammadBilall/Lab01/blob/master/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
arr = np.array([
                [10,20],
                [30,40],
                [50,60],
                [70,80]
                ])
print(arr)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [10]:
from numpy.random import randint
arr2 = randint(1,10,10)
print(arr2)

ascendingOrder = np.sort(arr2)
print("ascending sorting: ", ascendingOrder)
print("descending sorting: ", ascendingOrder[::-1])

[3 5 7 8 6 9 2 8 2 6]
ascending sorting:  [2 2 3 5 6 6 7 8 8 9]
descending sorting:  [9 8 8 7 6 6 5 3 2 2]


In [15]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])
print(arr3)
arr3 = np.reshape(arr3, (-1,3))
print(arr3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
arr4 = np.array([1,2,3,4])
arr5 = np.array([5,6,7,8])
print (arr4, arr5)

colStackedArray = np.column_stack((arr4, arr5))
rowStackedArray = np.row_stack((arr4, arr5))

print(colStackedArray, "\n",rowStackedArray)

[1 2 3 4] [5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]] 
 [[1 2 3 4]
 [5 6 7 8]]


In [21]:
arr6 = randint(1,10,10)
arr7 = randint(1,10,10)
print(arr6,"\n",arr7)
print("common elements in both arrays: ", np.intersect1d(arr6, arr7))

[6 4 6 4 5 9 4 2 4 1] 
 [5 6 4 8 2 1 2 7 7 5]
common elements in both arrays:  [1 2 4 5 6]


In [29]:
arr8 = np.array([
              randint(1,50,5),
              randint(1,50,5),
              randint(1,50,5),
              randint(1,50,5),
              randint(1,50,5)
              ])
print(arr8)
print("max value in columns: ", np.amax(arr8, axis=0))
print("max value in rows: ", np.amax(arr8, axis=1))
print("min value in columns: ", np.amin(arr8, axis=0))
print("min value in rows: ", np.amin(arr8, axis=1))

[[29  1 45  1 27]
 [24 12 18 49 26]
 [36  2 39 49 39]
 [19 19 40 49 45]
 [21 20 16 19  4]]
max value in columns:  [36 20 45 49 45]
max value in rows:  [45 49 49 49 21]
min value in columns:  [19  1 16  1  4]
min value in rows:  [ 1 12  2 19  4]


In [31]:
arr9 = randint(1,100,100)
print("mean: ", np.mean(arr9))
print("mean: ", np.median(arr9))
print("mean: ", np.std(arr9))

mean:  48.1
mean:  49.5
mean:  27.69350104266342


In [35]:
arr10 = np.array([
              randint(1,50,5),
              randint(1,50,5),
              randint(1,50,5),
              randint(1,50,5),
              randint(1,50,5)
              ])
print("Matrix:\n",arr10)
arr10 = arr10 - np.mean(arr10,axis=0)
arr10 = arr10 / np.abs(arr10).max(axis=0)
print("Normalized Matrix:\n",arr10)

Matrix:
 [[ 8 35 11 30 46]
 [32 17 12 29 28]
 [33  6 38  3  8]
 [ 1 16 15 10 24]
 [35 28 29  3 37]]
Normalized Matrix:
 [[-0.66346154  1.         -0.58823529  1.          0.84466019]
 [ 0.49038462 -0.23287671 -0.52941176  0.93333333 -0.02912621]
 [ 0.53846154 -0.98630137  1.         -0.8        -1.        ]
 [-1.         -0.30136986 -0.35294118 -0.33333333 -0.22330097]
 [ 0.63461538  0.52054795  0.47058824 -0.8         0.40776699]]


In [71]:
array11 = np.random.random((4,4,3))
array12 = np.random.random((4,4))

print(array11)
print(array12)

array13 = array11.reshape(12,4).T
array14 = np.matmul(array12,array13)

print(array14)

[[[0.87109631 0.01999909 0.47298561]
  [0.21966948 0.79418247 0.73451847]
  [0.25939612 0.65529804 0.33161695]
  [0.17037636 0.16676968 0.26684578]]

 [[0.07764351 0.35652983 0.76658894]
  [0.66753135 0.75851142 0.82917966]
  [0.50432374 0.46528941 0.68470478]
  [0.95074637 0.26764742 0.36007903]]

 [[0.63362084 0.23173301 0.73943472]
  [0.57133619 0.7162871  0.9912891 ]
  [0.26074482 0.2139823  0.60331816]
  [0.8564219  0.18633949 0.17238267]]

 [[0.99211707 0.74761335 0.97894949]
  [0.4807429  0.86137872 0.98333196]
  [0.2013237  0.60830013 0.37198068]
  [0.10501979 0.13666174 0.24791693]]]
[[0.53550004 0.70937192 0.80251395 0.12526462]
 [0.94592006 0.54441734 0.58913149 0.12391817]
 [0.08006274 0.75112546 0.03233385 0.1683237 ]
 [0.79358214 0.72072055 0.89155314 0.93194872]]
[[0.88775326 1.23658619 0.46570243 0.99330674 1.45739081 1.30098818
  1.16866377 1.32282019 1.10173204 1.90745535 1.39657999 0.41442193]
 [1.14074708 1.38513948 0.53775528 0.80188653 1.52368177 1.36757866
  1.23